.TH "EDGES" "1" "2021-09-06" "edges 2.0.2" "User Commands"
.SH NAME
edges - set up hot-corners
.SH SYNOPSIS
\fBedges\fR [FLAGS] [OPTIONS]
.SH DESCRIPTION
With edges you can configure hot-corners independently from your Desktop Environment
or Window Manager. The commands can be passed as arguments or read from a configuration
file.
.SH "FLAGS"
.TP
\fB\-b\fR, \fB\-\-block\fR
Block until a command exits
.TP
\fB\-c\fR, \fB\-\-config\fR
Read commands from config file
.TP
\fB\-d\fR, \fB\-\-debug\fR
Prints debug information
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Prints version information
.SH "OPTIONS"
.TP
\fB\-\-bottom\fR <CMD>
Bottom edge command
.TP
\fB\-\-bottomleft\fR <CMD>
Bottom left corner command
.TP
\fB\-\-bottomright\fR <CMD>
Bottom right corner command
.TP
\fB\-\-left\fR <CMD>
Left edge command
.TP
\fB\-\-right\fR <CMD>
Right edge command
.TP
\fB\-\-top\fR <CMD>
Top edge command
.TP
\fB\-\-topleft\fR <CMD>
Top left corner command
.TP
\fB\-\-topright\fR <CMD>
Top right corner comma
.SH FILES
.IP "\fB$HOME/.config/edges.conf\fR"
The configuration file that is used by the --config flag.
The file must be created manually.
.PP
.RS
Example:
.nf

[Commands]
topleft = skippy-xd
topright =
bottomright =
bottomleft =
left =
top =
right =
bottom =

.fi
.RE
.SH MULTI MONITOR
Multi monitor support is experimental only. Do not expect it to work properly in all setups.
.SH AUTHOR
Written by Michael Straube.
.SH COPYRIGHT
MIT License <https://opensource.org/licenses/MIT>.
